### PR TITLE
Refactor to support additional features

### PR DESCRIPTION
**Pull request by antonlindstrom**
This is a refactor to support additional features and to clean up the
app a bit. The changes are rather big and changes how the command line
works.

Thank you for working on this, it has helped a lot working with timers!

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks! I'll have a look soon-ish ...

**Comment by tebeka** [comment]
Hi @antonlindstrom ,

I have a few remarks, they come from my personal preferences - so you might disagree :)

In general, I'd like to stay within the limits of the standard library. Every dependency is a liability and unless there is a really good reason to include - I'm inclined to skip. You've added two libraries:
- `when`: A combination of `time.Parse` and `duration.Parse` will do most of the work
- `cli`: I really don't see the benefit here over `flag`

Also, currently the tests do not pass since these libraries are not vendored.

The second thing is splitting the code to a library and several files. I can see the value of a library but never got a request for it - do you have a need?
I also don't see the value of moving two functions to a different file `config.go`. Currently `toggle.go` is 280 lines which not too big.

I'd love to add the extra functionality, but it'll require a big change to this PR.


Thanks again for taking the time to make `toggl` better.

**Comment by antonlindstrom** [comment]
Hi @tebeka,

Thank you for taking the time to look at this! I will try to see if I can do the changes in a while. In the meantime, do you want me to close this PR and reopen it later on when it better suits the style that you describe?

Again, thank you for taking the time to look at this!

**Comment by tebeka** [comment]
Sure, close this one another when you're ready.

**Pull request closed without merging**
